### ISSUE TITLE
Admin Panel Metaissue

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#151]
The admin panel should 
- [ ] Allow the user to create and manage races (offices to which people are being elected)
- [ ] Allow the user to create and manage candidates
- [ ] Allow the user to create and manage surveys 
- [ ] Allow the user to create and manage geographic regions
. . .

**Comment by stanzheng** [comment]
Since its mid september we should take inventory if we're going to be able to hit this goal by early october to be worth doing?

I volunteer to help with data entry if we decide to do it like we did last cycle.

**Comment by wbprice** [comment]
We're just going to enter all the data manually again this cycle. No point
in stressing our resources.

On Sep 14, 2016 8:27 PM, "Stanley Zheng" <notifications@github.com> wrote:

Since its mid september we should take inventory if we're going to be able
to hit this goal by early october to be worth doing?

I volunteer to help with data entry if we decide to do it like we did last
cycle.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Code4HR/okcandidate/issues/151#issuecomment-247197822>,
or mute the thread
