### ISSUE TITLE
Election Day Reminder Flow

### ISSUE THREAD

**Issue by wbprice** [Code4HR/okcandidate#177]
![election reminder flow](https://cloud.githubusercontent.com/assets/2590422/18151673/ccb0c880-6fbe-11e6-9ab5-2a2dd03dc10f.png)

@kmoretz I'll split this into three issues, but this is the general flow I have in mind.
- [x] Election Day Reminder Prompt #180 
- [x] Election Day Reminder Form #181 
- [x] Election Day Reminder Submitted #182
